export const CHANGE_DIRECTION_REQUEST = 'CHANGE_DIRECTION_REQUEST';
export const CHANGE_DIRECTION_SUCCESS = 'CHANGE_DIRECTION_SUCCESS';
export const CHANGE_DIRECTION_FAILURE = 'CHANGE_DIRECTION_FAILURE';